### ISSUE TITLE
Could not open library 'hidapi'

### ISSUE THREAD

**Issue by dounokouno** [kurain/co2mini#1]
初めまして。 @dounokouno と申します。

日本人とお見受けし、日本語で失礼いたします。

下記の記事を拝見しまして、私も Raspberry Pi + CO2mini という構成で Raspberry Pi から CO2mini の値を取得したいと考えております。（私もモノタロウで CO2mini を購入しました。）

http://r-kurain.hatenablog.com/entry/2016/01/26/164648

上記の記事の通り作業を行ったのですが、うまく値を取得することができなかったため、もし何かご存知のことがあればご教示いただければと思い、 issue を立てさせていただきました。

Raspberry Pi のモデルは Raspberry Pi 2 です。

Ruby は 2.5.0 を利用しています。

HIDAPI は https://github.com/signal11/hidapi からソースを clone して、 make してインストールをしました。

また、 https://github.com/kurain/co2mini のソースも clone 済みです。

その状態で https://github.com/kurain/co2mini のサンプルスクリプトを実行しますと、 HIDAPI のインストールがうまくいっていないのか、 `Could not open library 'hidapi'` と言われてしまいました。

```
pi@airpi2:~/co2mini/example$ bundle exec ruby -I../lib ./co2show.rb
Traceback (most recent call last):
	8: from ./co2show.rb:1:in `<main>'
	7: from ./co2show.rb:1:in `require'
	6: from /home/pi/co2mini/lib/co2mini.rb:2:in `<top (required)>'
	5: from /home/pi/co2mini/lib/co2mini.rb:2:in `require'
	4: from /home/pi/co2mini/example/vendor/bundle/ruby/2.5.0/bundler/gems/ruby_hid_api-959abe528e37/lib/hid_api.rb:3:in `<top (required)>'
	3: from /home/pi/co2mini/example/vendor/bundle/ruby/2.5.0/bundler/gems/ruby_hid_api-959abe528e37/lib/hid_api.rb:7:in `<module:HidApi>'
	2: from /home/pi/co2mini/example/vendor/bundle/ruby/2.5.0/gems/ffi-1.9.10/lib/ffi/library.rb:100:in `ffi_lib'
	1: from /home/pi/co2mini/example/vendor/bundle/ruby/2.5.0/gems/ffi-1.9.10/lib/ffi/library.rb:100:in `map'
/home/pi/co2mini/example/vendor/bundle/ruby/2.5.0/gems/ffi-1.9.10/lib/ffi/library.rb:133:in `block in ffi_lib': Could not open library 'hidapi': hidapi: cannot open shared object file: No such file or directory. (LoadError)
Could not open library 'libhidapi.so': libhidapi.so: cannot open shared object file: No such file or directory
```

hidapi のインストールされたディレクトリを確認してみたところ、 libhidapi.so というファイルは見つかりませんでした。

```
pi@airpi2:~$ ls -la /usr/local/lib/
合計 196
drwxrwsr-x  7 root staff  4096  1月  8 18:16 .
drwxrwsr-x 10 root staff  4096  1月 30  2015 ..
-rw-r--r--  1 root staff 30010  1月  8 15:35 libhidapi-hidraw.a
-rwxr-xr-x  1 root staff  1004  1月  8 15:35 libhidapi-hidraw.la
lrwxrwxrwx  1 root staff    25  1月  8 15:35 libhidapi-hidraw.so -> libhidapi-hidraw.so.0.0.0
lrwxrwxrwx  1 root staff    25  1月  8 15:35 libhidapi-hidraw.so.0 -> libhidapi-hidraw.so.0.0.0
-rwxr-xr-x  1 root staff 31845  1月  8 15:35 libhidapi-hidraw.so.0.0.0
-rw-r--r--  1 root staff 47222  1月  8 15:35 libhidapi-libusb.a
-rwxr-xr-x  1 root staff  1021  1月  8 15:35 libhidapi-libusb.la
lrwxrwxrwx  1 root staff    25  1月  8 15:35 libhidapi-libusb.so -> libhidapi-libusb.so.0.0.0
lrwxrwxrwx  1 root staff    25  1月  8 15:35 libhidapi-libusb.so.0 -> libhidapi-libusb.so.0.0.0
-rwxr-xr-x  1 root staff 48823  1月  8 15:35 libhidapi-libusb.so.0.0.0
drwxr-sr-x  3 root staff  4096  3月  3  2015 perl
drwxr-sr-x  2 root staff  4096  1月  8 15:35 pkgconfig
drwxrwsr-x  4 root staff  4096  2月 21  2017 python2.7
drwxrwsr-x  3 root staff  4096  2月  1  2015 python3.2
drwxr-sr-x  3 root staff  4096 10月 12  2015 site_ruby
```

以上です。

他にも必要な情報がありましたら、調べてお伝えできればと思います。
お手数をおかけいたしますが、ご確認いただければ幸いでございます。

**Comment by sakaguti** [comment]
sudo apt-get install   libhidapi-dev libhidapi-hidraw0-dbg libhidapi-libusb0 libhidapi-libusb0-dbg

**Comment by felidae** [comment]
同様にRaspberry Piとの組み合わせで解決したので参考までに。
bundlerでGemfileを以下のようにしました。

```ruby
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "hid_api", github: "kurain/ruby_hid_api", branch: "feature_report"
gem "co2mini", github: "kurain/co2mini"
```

libhidapi.soはlibhidapi-libusb.soに名前が変更されたのかruby_hid_api gemのlib/hid_api.rbを
```sed -e s/ffi_lib 'hidapi'/ffi_lib 'hidapi-libusb'/```のようにしroot権限で値が取得できました。

**Comment by naosone** [comment]
Raspbian GNU/Linux 10 (buster)では、libhidapi-hidraw0を使って値の取得ができました。
lib/hid_api.rbの修正は
`sed -i -e "s/ffi_lib 'hidapi'/ffi_lib 'hidapi-hidraw'" hid_api.rb`
で成功しました。

**Comment by dounokouno** [comment]
私のはじめの投稿から1年以上が経ちましたが、 ↑ のお二人の投稿を元に解決することができました。

# Raspberry Pi のモデル

- Raspberry Pi 4 Model B 4GB

# OS

```
$ cat /etc/debian_version 
10.3
```

# Ruby

```
$ ruby -v
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [armv7l-linux-eabihf]
$ which ruby
/home/pi/.anyenv/envs/rbenv/shims/ruby
```

# インストールしたライブラリ

```
$ sudo apt install -y libhidapi-dev libhidapi-hidraw0 libhidapi-libusb0
```

# コード

## Gemfile

```
# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'hid_api', github: 'dounokouno/ruby_hid_api', branch: 'add_other_hidapi_libs_branched_from_feature_report'
gem 'co2mini', github: 'kurain/co2mini'
```

※ブランチ名が少々長いですが、 `ffi_lib` で読み込むライブラリを修正したブランチ https://github.com/dounokouno/ruby_hid_api/tree/add_other_hidapi_libs_branched_from_feature_report を作りました。このブランチの修正内容は本家に PR 済み。

## co2show.rb

co2show.rb はサンプルコード（ https://github.com/kurain/co2mini/blob/master/example/co2show.rb ）のまま。

```
require 'co2mini'

dev = CO2mini.new

dev.on(:co2) do |op, val|
  puts "CO2 #{val}"
end

dev.on(:temp) do |op, val|
  puts "Temperature #{val}"
end

dev.loop
```

# 実行方法と実行結果

@felidae 様のおっしゃるとおり、 root 権限でしか値を取得できなかったので、 `sudo` にて実行。

```
sudo sh -c "/home/pi/.anyenv/envs/rbenv/shims/bundle exec --gemfile=/home/pi/co2mini2/Gemfile ruby co2show.rb"
[DEPRECATION] Struct layout is already defined for class HidApi::DeviceInfo. Redefinition as in /home/pi/co2mini2/vendor/bundle/ruby/2.7.0/bundler/gems/ruby_hid_api-fcb4997bee3c/lib/hid_api/device_info.rb:31:in `<class:DeviceInfo>' will be disallowed in ffi-2.0.
Temperature 25.225000000000023
CO2 674
```

---

以上で issue の内容は解決しましたので、 close させていただきますmm
